package com.example.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.database.GoodsBean;
import com.example.database.User;

import com.example.database.GoodsBeanDao;
import com.example.database.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GoodsBeanDao goodsBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsBeanDaoConfig = daoConfigMap.get(GoodsBeanDao.class).clone();
        goodsBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        goodsBeanDao = new GoodsBeanDao(goodsBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(GoodsBean.class, goodsBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        goodsBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public GoodsBeanDao getGoodsBeanDao() {
        return goodsBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
